INI_CONFIGS_PATH = 'C:/Users/kasthuri.kandavelu/PycharmProjects/python-automation-project/swaglabs/ini_configs/propos.ini'
LOCATORS_CONFIGS_PATH = 'C:/Users/kasthuri.kandavelu/PycharmProjects/python-automation-project/swaglabs/ini_configs/locators.ini'
DATA_FILES_PATH = 'C:/Users/kasthuri.kandavelu/PycharmProjects/python-automation-project/swaglabs/data/test_data.json'
LOGGER_PATH = 'C:/Users/kasthuri.kandavelu/PycharmProjects/python-automation-project/swaglabs/logs'
LOGGING_YAML_FILE_PATH = 'C:/Users/kasthuri.kandavelu/PycharmProjects/python-automation-project/swaglabs/configuration/logging.yaml'
LOGGER_FILE_NAME = 'automation.log'
